# Generated by Django 4.2.5 on 2023-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='unique_npm',
            field=models.IntegerField(),
        ),
    ]
