# Generated by Django 4.2.5 on 2023-09-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_delete_person_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
